# Generated by Django 5.0.7 on 2024-08-01 08:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinLengthValidator(1)])),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('designation', models.CharField(choices=[('Employee', 'Employee'), ('Lead', 'Lead'), ('Manager', 'Manager')], max_length=10)),
                ('role', models.CharField(blank=True, choices=[('Developer', 'Developer'), ('Designer', 'Designer'), ('Tester', 'Tester')], max_length=20, null=True)),
                ('password', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(6)])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.project')),
            ],
        ),
    ]
